name: Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install rustup and cargo-binstall
      run: |
        curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
        source "$HOME/.cargo/env"
        rustup update
        curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

    - name: Install mdBook
      run: cargo binstall mdbook --no-confirm

    - name: Build Documentation
      run: |
        mdbook build --dest-dir book_build
        # 验证生成的目录结构
        ls -l book_build

    - name: Install Compression Tools
      run: sudo apt-get update && sudo apt-get install -y zip rar

    - name: Package Documentation
      run: |
        mkdir -p artifacts
        
        # 处理可能的路径差异
        if [ -d "book_build/book" ]; then
          # 大多数情况下的标准路径
          zip -r artifacts/book.zip book_build/book
          rar a -r artifacts/book.rar book_build/book
        elif [ -d "book_build" ]; then
          # 备选路径
          zip -r artifacts/book.zip book_build
          rar a -r artifacts/book.rar book_build
        else
          echo "构建目录未找到!"
          ls .
          exit 1
        fi
        
        echo "打包完成，目录结构:"
        ls -l artifacts

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: ${{ !contains(github.ref, '-stable') }}
        files: |
          artifacts/book.zip
          artifacts/book.rar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
